geodjango/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',TemplateView.as_view(template_name='poll_stations/index.html')),
    path('stations/',include('poll_stations.urls'))
]

poll_stations/urls.py
from . import views
from django.urls import path, include
app_name= "poll_stations"
urlpatterns = [
    path('', views.stations, name='stations'),
    # path('geojson', views.station_api, name='stations_api'),
    path('api', views.StationApi.as_view(), name='api'),
    path('station_data', views.StationDataApi.as_view(), name='station_data'),
]

poll_stations/models.py
# from django.db import models
from django.contrib.gis.db import models

# Create your models here.
class Stations(models.Model):
    
    #geometry coloum
    geom = models.PointField()
    country = models.CharField(max_length=50)
    state = models.CharField(max_length=50)
    city = models.CharField(max_length=50)
    station = models.CharField(max_length=200)
    lon = models.FloatField()
    lat = models.FloatField()


    def __str__(self)->str:
        """this method will give reprentative text of the object"""
        return self.station +"_"+ self.city

poll_stations/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Stations
from django.core.serializers import serialize
from geodjango.settings import API_KEY
from rest_framework.views import APIView
from rest_framework import status
from rest_framework.response import Response
from rest_framework.status import HTTP_200_OK
from .serializers import StationDataSerializer, StationSerializer
from rest_framework import generics


def stations(request)->HttpResponse:
    """
    this function is responsible to fetch the station points from the database and 
    send them as a geojson
    """
    return render(request=request, template_name='poll_stations/map.html')

class StationDataApi(APIView):
    """
        this class will handle the station related Live data supported by Govt of india 
        API
    """
    def get(self, request, format=None)->Response:
        station = Stations.objects.all()
        serializer = StationDataSerializer(station, many= True)
        return Response(serializer.data)


class StationApi(generics.ListAPIView):
    # def get(self, request, format=None):
    #     # station = serialize("geojson", Stations.objects.all())

    #     # return Response(station, status=HTTP_200_OK)
        
    queryset = Stations.objects.all()
    serializer_class = StationDataSerializer

poll_stations/templates/poll_stations/index.html
{% extends 'poll_stations/main.html' %}
{% block title %}Welcome Page {% endblock %}
{% block header %}
{% load static %}
    <!-- <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css"> -->
    <style>
    .charcter{
        text-transform: uppercase;
        text-align: center;
        background-image: linear-gradient(
            -225deg,
            #78f1b5 0%,
            #f0ad30 29%,
            #ff1361 67%,
            #fff800 100%
        );

        background-size: auto auto;
        background-clip: border-box;
        background-size: 200% auto;
        color: #fff;
        background-clip: text;
        /* text-fill-color: transparent; */
        -webkit-background-clip: text;
        -webkit-text-fill-color: transparent;
        animation: textclip 2s linear infinite;
        font-size: 50px;
        }

@keyframes textclip {
  to {
    background-position: 200% center;
  }
}
.hero-section {
        background-image: url("{% static 'poll_stations/images/hero.jpg' %}");
        background-size: cover;
        background-position: center;
        height: 100vh; /* Set the height to full viewport height */
        display: flex;
        justify-content: center;
        align-items: center;
    }

</style>
{% endblock %}
{% block body %}
<div class="hero-section">
  <div class="p-5 text-center bg-image hero-image h-100">
    <div class="d-flex justify-content-center align-items-center h-100">
      <div class="text-white">
        <h1 class="mb-3">Real Time Pollution Display System</h1>
        <h4 class="mb-3">Map View of Real time Pollution Monitering System. Powered By Govt Of india Data API.</h4>
        <a data-mdb-ripple-init class="charcter " href="{% url 'poll_stations:stations' %}" role="button">Jump To The Map View.</a>
      </div>
  </div>
</div>
</div>

{% endblock %}

poll_stations/templates/poll_stations/main.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title%}{% endblock %}</title>
    {% block header %}{% endblock %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body>
    {% block body %}{% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>

poll_stations/templates/poll_stations/map.html
<!-- extend base html -->
{% extends 'poll_stations/main.html' %}
{% load static %}
<!-- Adding header in the html document  -->
{% block title %} Pollution Level Capture Stations {% endblock %}
<!-- start of header scripts -->
{% block header %}
<link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css"
    integrity="sha256-p4NxAoJBhIIN+hmNHrzRCf9tD/miZyoHS5obTRR9BMY=" crossorigin="" />

<link rel="stylesheet" href="{% static 'poll_stations/css/L.Control.Sidebar.css' %}">

<!-- Make sure you put this AFTER Leaflet's CSS -->
<script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"
    integrity="sha256-20nQCchB9co0qIjJZRGuk2/Z9VM+kNiyxNV1lvTlZBo=" crossorigin=""></script>

<script src='https://cdnjs.cloudflare.com/ajax/libs/leaflet.markercluster/1.5.3/leaflet.markercluster.js'></script>
<link href='https://cdnjs.cloudflare.com/ajax/libs/leaflet.markercluster/1.5.3/MarkerCluster.css' rel='stylesheet' />
<link href='https://cdnjs.cloudflare.com/ajax/libs/leaflet.markercluster/1.5.3/MarkerCluster.Default.css'
    rel='stylesheet' />

<style>
    html,
    body {
        height: 100%;
        margin: 0;
    }

    #map {
        position: block;
        margin: auto;
        height: 100%;
        width: 100%;
    }

    #marker-info {
        position: absolute;
        top: 10px;
        right: 10px;
        padding: 10px;
        background-color: white;
        border: 1px solid #ccc;
        box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
        max-width: 300px;
        z-index: auto;
    }

    #close-marker-info {
        position: absolute;
        top: 5px;
        right: 5px;
        cursor: pointer;
        font-size: 16px;
        color: #999;
        border: none;
        background: none;
        z-index: 1000;
    }

    #close-marker-info:hover {
        color: #333;
    }
    /* Add this to your CSS file or style section */
    /* .progress-bar-container {
        width: 100%;
        height: 20px;
        background-color: #f0f0f0;
        margin-top: 5px;
    } */

    /* .progress-bar {
        height: 100%;
        background-color: #4caf50; /* Green color for progress 
    } */
    .minValue {
        right: 0;
        margin-right: 10px;
        padding-bottom: 2px;
    }
    .maxValue {
        left: 0;
        margin-left: 10px;
        padding-bottom: 2px;

    }
    .avgValue{
        padding-left: 5px;
    }


</style>
<script src="{% static 'poll_stations/js/script.js' %}"></script>
<script src="{% static 'poll_stations/js/L.Control.Sidebar.js' %}"></script>
{% endblock %}
<!-- end header scripts  -->

<!-- Body start  -->
{% block body %}
<div id="map"></div>

<div id="sidebar" class="d-flex flex-column flex-shrink-0 p-3 bg-body-tertiary">

    <h2 id="station_header">Real Time Pollution Status</h2>
    <hr>
    <ul class="nav nav-pills flex-column mb-auto">
        <li id="country" class="nav-item"></li>
        <li id="state"></li>
        <li id="city"></li>
        <li id="station"></li>
        <li id="last_updated"></li>
    </ul>
    <hr>
    <div id="pollutants-container"></div>
</div>



<script>
    var iconImage = '{% static "poll_stations/images/chimney.png"  %}';
</script>

{% endblock %}